export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST';
export const SET_PRODUCTLINE_LIST = 'SET_PRODUCTLINE_LIST';
export const SET_LINESPECS_LIST = 'SET_LINESPECS_LIST';
export const SET_MODEL_LIST = 'SET_MODEL_LIST';

export const SET_MODEL_TYPE = 'SET_MODEL_TYPE';
export const SET_MODEL_DETAILS = 'SET_MODEL_DETAILS';
export const SET_MODEL = 'SET_MODEL';
export const SET_MANUFACTURER = 'SET_MANUFACTURER';
export const FETCH_START = 'FETCH_START'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

